# Generated by Django 3.0.7 on 2020-06-06 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gstbillingapp', '0010_auto_20200319_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_carton_size',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
